version: '3.4'  

services:
  install:
    image: node:carbon-jessie-slim
    volumes:
      - ./:/app
    working_dir: /app
    command: "npm install"
  anitracker:
    image: nginx:stable
    volumes: 
      - ./dev.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    ports:
      - "8088:80"
    command: "nginx -g 'daemon off;'"