version: '3.4'  

services:
  build:
    image: huli/grunt:alpine
    volumes: 
      - ./:/srv
    working_dir: /srv
    command: "build"
  anitracker:
    image: nginx:stable
    volumes: 
      - ./dev.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "8088:80"
    command: "nginx -g 'daemon off;'"
    depends_on:
      - build